// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAppointmentsByUserAndDate = `-- name: CountAppointmentsByUserAndDate :one
SELECT COUNT(*) FROM appointments
WHERE user_id = $1 AND date = $2 AND status NOT IN ('cancelled', 'no-show')
`

type CountAppointmentsByUserAndDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) CountAppointmentsByUserAndDate(ctx context.Context, arg CountAppointmentsByUserAndDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppointmentsByUserAndDate, arg.UserID, arg.Date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    salon_id,
    user_id,
    service_id,
    client_name,
    client_phone,
    client_email,
    date,
    start_time,
    end_time,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at
`

type CreateAppointmentParams struct {
	SalonID     uuid.UUID         `json:"salon_id"`
	UserID      uuid.UUID         `json:"user_id"`
	ServiceID   uuid.UUID         `json:"service_id"`
	ClientName  string            `json:"client_name"`
	ClientPhone string            `json:"client_phone"`
	ClientEmail sql.NullString    `json:"client_email"`
	Date        time.Time         `json:"date"`
	StartTime   time.Time         `json:"start_time"`
	EndTime     time.Time         `json:"end_time"`
	Status      AppointmentStatus `json:"status"`
	Notes       sql.NullString    `json:"notes"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment,
		arg.SalonID,
		arg.UserID,
		arg.ServiceID,
		arg.ClientName,
		arg.ClientPhone,
		arg.ClientEmail,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.UserID,
		&i.ServiceID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ClientEmail,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments
WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAppointment, id)
	return err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id uuid.UUID) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.UserID,
		&i.ServiceID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ClientEmail,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listAppointmentsByClientPhone = `-- name: ListAppointmentsByClientPhone :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE salon_id = $1 AND client_phone = $2
ORDER BY date DESC, start_time DESC
`

type ListAppointmentsByClientPhoneParams struct {
	SalonID     uuid.UUID `json:"salon_id"`
	ClientPhone string    `json:"client_phone"`
}

func (q *Queries) ListAppointmentsByClientPhone(ctx context.Context, arg ListAppointmentsByClientPhoneParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByClientPhone, arg.SalonID, arg.ClientPhone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByDate = `-- name: ListAppointmentsByDate :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE salon_id = $1 AND date = $2
ORDER BY start_time
`

type ListAppointmentsByDateParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
}

func (q *Queries) ListAppointmentsByDate(ctx context.Context, arg ListAppointmentsByDateParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByDate, arg.SalonID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByDateRange = `-- name: ListAppointmentsByDateRange :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE salon_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date, start_time
`

type ListAppointmentsByDateRangeParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

func (q *Queries) ListAppointmentsByDateRange(ctx context.Context, arg ListAppointmentsByDateRangeParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByDateRange, arg.SalonID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsBySalonID = `-- name: ListAppointmentsBySalonID :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE salon_id = $1
ORDER BY date DESC, start_time DESC
`

func (q *Queries) ListAppointmentsBySalonID(ctx context.Context, salonID uuid.UUID) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsBySalonID, salonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByStatus = `-- name: ListAppointmentsByStatus :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE salon_id = $1 AND status = $2
ORDER BY date DESC, start_time DESC
`

type ListAppointmentsByStatusParams struct {
	SalonID uuid.UUID         `json:"salon_id"`
	Status  AppointmentStatus `json:"status"`
}

func (q *Queries) ListAppointmentsByStatus(ctx context.Context, arg ListAppointmentsByStatusParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByStatus, arg.SalonID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByUser = `-- name: ListAppointmentsByUser :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE user_id = $1 AND date = $2
ORDER BY start_time
`

type ListAppointmentsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) ListAppointmentsByUser(ctx context.Context, arg ListAppointmentsByUserParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByUser, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByUserAndDateRange = `-- name: ListAppointmentsByUserAndDateRange :many
SELECT id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at FROM appointments
WHERE user_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date, start_time
`

type ListAppointmentsByUserAndDateRangeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) ListAppointmentsByUserAndDateRange(ctx context.Context, arg ListAppointmentsByUserAndDateRangeParams) ([]Appointment, error) {
	rows, err := q.db.QueryContext(ctx, listAppointmentsByUserAndDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.UserID,
			&i.ServiceID,
			&i.ClientName,
			&i.ClientPhone,
			&i.ClientEmail,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET 
    date = COALESCE($2, date),
    start_time = COALESCE($3, start_time),
    end_time = COALESCE($4, end_time),
    status = COALESCE($5, status),
    notes = COALESCE($6, notes)
WHERE id = $1
RETURNING id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at
`

type UpdateAppointmentParams struct {
	ID        uuid.UUID             `json:"id"`
	Date      sql.NullTime          `json:"date"`
	StartTime sql.NullTime          `json:"start_time"`
	EndTime   sql.NullTime          `json:"end_time"`
	Status    NullAppointmentStatus `json:"status"`
	Notes     sql.NullString        `json:"notes"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointment,
		arg.ID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.UserID,
		&i.ServiceID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ClientEmail,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, salon_id, user_id, service_id, client_name, client_phone, client_email, date, start_time, end_time, status, notes, created_at
`

type UpdateAppointmentStatusParams struct {
	ID     uuid.UUID         `json:"id"`
	Status AppointmentStatus `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.UserID,
		&i.ServiceID,
		&i.ClientName,
		&i.ClientPhone,
		&i.ClientEmail,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
