// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    salon_id,
    name,
    phone,
    email,
    birthday
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at
`

type CreateClientParams struct {
	SalonID  uuid.UUID      `json:"salon_id"`
	Name     string         `json:"name"`
	Phone    string         `json:"phone"`
	Email    sql.NullString `json:"email"`
	Birthday sql.NullTime   `json:"birthday"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.SalonID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Birthday,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Birthday,
		&i.TotalAppointments,
		&i.LastAppointment,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClient, id)
	return err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at FROM clients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Birthday,
		&i.TotalAppointments,
		&i.LastAppointment,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByPhone = `-- name: GetClientByPhone :one
SELECT id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at FROM clients
WHERE salon_id = $1 AND phone = $2 LIMIT 1
`

type GetClientByPhoneParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Phone   string    `json:"phone"`
}

func (q *Queries) GetClientByPhone(ctx context.Context, arg GetClientByPhoneParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByPhone, arg.SalonID, arg.Phone)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Birthday,
		&i.TotalAppointments,
		&i.LastAppointment,
		&i.CreatedAt,
	)
	return i, err
}

const listClientsBySalonID = `-- name: ListClientsBySalonID :many
SELECT id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at FROM clients
WHERE salon_id = $1
ORDER BY name
`

func (q *Queries) ListClientsBySalonID(ctx context.Context, salonID uuid.UUID) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClientsBySalonID, salonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Birthday,
			&i.TotalAppointments,
			&i.LastAppointment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClientsByName = `-- name: SearchClientsByName :many
SELECT id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at FROM clients
WHERE salon_id = $1 AND name ILIKE '%' || $2 || '%'
ORDER BY name
LIMIT 50
`

type SearchClientsByNameParams struct {
	SalonID uuid.UUID      `json:"salon_id"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchClientsByName(ctx context.Context, arg SearchClientsByNameParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClientsByName, arg.SalonID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Birthday,
			&i.TotalAppointments,
			&i.LastAppointment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClientsByPhone = `-- name: SearchClientsByPhone :many
SELECT id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at FROM clients
WHERE salon_id = $1 AND phone LIKE '%' || $2 || '%'
ORDER BY name
LIMIT 50
`

type SearchClientsByPhoneParams struct {
	SalonID uuid.UUID      `json:"salon_id"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) SearchClientsByPhone(ctx context.Context, arg SearchClientsByPhoneParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, searchClientsByPhone, arg.SalonID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Birthday,
			&i.TotalAppointments,
			&i.LastAppointment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET 
    name = COALESCE($2, name),
    phone = COALESCE($3, phone),
    email = COALESCE($4, email),
    birthday = COALESCE($5, birthday)
WHERE id = $1
RETURNING id, salon_id, name, phone, email, birthday, total_appointments, last_appointment, created_at
`

type UpdateClientParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     sql.NullString `json:"name"`
	Phone    sql.NullString `json:"phone"`
	Email    sql.NullString `json:"email"`
	Birthday sql.NullTime   `json:"birthday"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Birthday,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Birthday,
		&i.TotalAppointments,
		&i.LastAppointment,
		&i.CreatedAt,
	)
	return i, err
}

const updateClientAppointmentStats = `-- name: UpdateClientAppointmentStats :exec
UPDATE clients
SET 
    total_appointments = total_appointments + 1,
    last_appointment = $2
WHERE id = $1
`

type UpdateClientAppointmentStatsParams struct {
	ID              uuid.UUID    `json:"id"`
	LastAppointment sql.NullTime `json:"last_appointment"`
}

func (q *Queries) UpdateClientAppointmentStats(ctx context.Context, arg UpdateClientAppointmentStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateClientAppointmentStats, arg.ID, arg.LastAppointment)
	return err
}
