// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_form.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createContactForm = `-- name: CreateContactForm :one
INSERT INTO contact_form (
    full_name,
    email,
    phone_number,
    salon_name,
    subject,
    message
  )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, email, phone_number, salon_name, subject, message, created_at, answered_at
`

type CreateContactFormParams struct {
	FullName    string             `json:"full_name"`
	Email       string             `json:"email"`
	PhoneNumber sql.NullString     `json:"phone_number"`
	SalonName   sql.NullString     `json:"salon_name"`
	Subject     ContactFormSubject `json:"subject"`
	Message     string             `json:"message"`
}

func (q *Queries) CreateContactForm(ctx context.Context, arg CreateContactFormParams) (ContactForm, error) {
	row := q.db.QueryRowContext(ctx, createContactForm,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.SalonName,
		arg.Subject,
		arg.Message,
	)
	var i ContactForm
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.SalonName,
		&i.Subject,
		&i.Message,
		&i.CreatedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const listContactForms = `-- name: ListContactForms :many
SELECT id, full_name, email, phone_number, salon_name, subject, message, created_at, answered_at
FROM contact_form
ORDER BY created_at DESC OFFSET $1
LIMIT $2
`

type ListContactFormsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListContactForms(ctx context.Context, arg ListContactFormsParams) ([]ContactForm, error) {
	rows, err := q.db.QueryContext(ctx, listContactForms, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactForm
	for rows.Next() {
		var i ContactForm
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.SalonName,
			&i.Subject,
			&i.Message,
			&i.CreatedAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactFormsHasNotResponded = `-- name: ListContactFormsHasNotResponded :many
SELECT id, full_name, email, phone_number, salon_name, subject, message, created_at, answered_at
FROM contact_form
WHERE answered_at IS NULL
ORDER BY created_at DESC OFFSET $1
LIMIT $2
`

type ListContactFormsHasNotRespondedParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListContactFormsHasNotResponded(ctx context.Context, arg ListContactFormsHasNotRespondedParams) ([]ContactForm, error) {
	rows, err := q.db.QueryContext(ctx, listContactFormsHasNotResponded, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactForm
	for rows.Next() {
		var i ContactForm
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.SalonName,
			&i.Subject,
			&i.Message,
			&i.CreatedAt,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
