// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dashboardActiveClients = `-- name: DashboardActiveClients :one
SELECT COUNT(DISTINCT client_phone)
FROM appointments
WHERE salon_id = $1 AND date >= $2 AND date < $3
`

type DashboardActiveClientsParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

func (q *Queries) DashboardActiveClients(ctx context.Context, arg DashboardActiveClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardActiveClients, arg.SalonID, arg.Date, arg.Date_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardAppointmentStatus = `-- name: DashboardAppointmentStatus :many
SELECT status, COUNT(*) AS count
FROM appointments
WHERE salon_id = $1 AND date >= $2 AND date < $3
GROUP BY status
`

type DashboardAppointmentStatusParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

type DashboardAppointmentStatusRow struct {
	Status AppointmentStatus `json:"status"`
	Count  int64             `json:"count"`
}

func (q *Queries) DashboardAppointmentStatus(ctx context.Context, arg DashboardAppointmentStatusParams) ([]DashboardAppointmentStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardAppointmentStatus, arg.SalonID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardAppointmentStatusRow
	for rows.Next() {
		var i DashboardAppointmentStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardEngagedClients = `-- name: DashboardEngagedClients :one
SELECT COUNT(*)
FROM (
    SELECT client_phone
    FROM appointments
    WHERE salon_id = $1 AND date >= $2 AND date < $3
    GROUP BY client_phone
    HAVING COUNT(*) >= 2
) t
`

type DashboardEngagedClientsParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

func (q *Queries) DashboardEngagedClients(ctx context.Context, arg DashboardEngagedClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardEngagedClients, arg.SalonID, arg.Date, arg.Date_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardNewClients = `-- name: DashboardNewClients :one
SELECT COUNT(*)
FROM clients
WHERE salon_id = $1 AND created_at >= $2 AND created_at < $3
`

type DashboardNewClientsParams struct {
	SalonID     uuid.UUID `json:"salon_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) DashboardNewClients(ctx context.Context, arg DashboardNewClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardNewClients, arg.SalonID, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardServiceCounts = `-- name: DashboardServiceCounts :many
SELECT a.service_id, COALESCE(s.name, '') AS name, COUNT(*) AS count
FROM appointments a
LEFT JOIN services s ON s.id = a.service_id
WHERE a.salon_id = $1 AND a.date >= $2 AND a.date < $3
GROUP BY a.service_id, s.name
ORDER BY count DESC
`

type DashboardServiceCountsParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

type DashboardServiceCountsRow struct {
	ServiceID uuid.UUID `json:"service_id"`
	Name      string    `json:"name"`
	Count     int64     `json:"count"`
}

func (q *Queries) DashboardServiceCounts(ctx context.Context, arg DashboardServiceCountsParams) ([]DashboardServiceCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, dashboardServiceCounts, arg.SalonID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardServiceCountsRow
	for rows.Next() {
		var i DashboardServiceCountsRow
		if err := rows.Scan(&i.ServiceID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardUniqueClients = `-- name: DashboardUniqueClients :one
SELECT COUNT(DISTINCT client_phone)
FROM appointments
WHERE salon_id = $1 AND date >= $2 AND date < $3
`

type DashboardUniqueClientsParams struct {
	SalonID uuid.UUID `json:"salon_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

func (q *Queries) DashboardUniqueClients(ctx context.Context, arg DashboardUniqueClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dashboardUniqueClients, arg.SalonID, arg.Date, arg.Date_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}
