// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AppointmentStatus string

const (
	AppointmentStatusPending   AppointmentStatus = "pending"
	AppointmentStatusConfirmed AppointmentStatus = "confirmed"
	AppointmentStatusCancelled AppointmentStatus = "cancelled"
	AppointmentStatusDone      AppointmentStatus = "done"
	AppointmentStatusNoShow    AppointmentStatus = "no-show"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	Valid             bool              `json:"valid"` // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type ContactFormSubject string

const (
	ContactFormSubjectSupport     ContactFormSubject = "support"
	ContactFormSubjectSales       ContactFormSubject = "sales"
	ContactFormSubjectPartnership ContactFormSubject = "partnership"
)

func (e *ContactFormSubject) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactFormSubject(s)
	case string:
		*e = ContactFormSubject(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactFormSubject: %T", src)
	}
	return nil
}

type NullContactFormSubject struct {
	ContactFormSubject ContactFormSubject `json:"contact_form_subject"`
	Valid              bool               `json:"valid"` // Valid is true if ContactFormSubject is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactFormSubject) Scan(value interface{}) error {
	if value == nil {
		ns.ContactFormSubject, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactFormSubject.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactFormSubject) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactFormSubject), nil
}

type NotificationStatus string

const (
	NotificationStatusQueued NotificationStatus = "queued"
	NotificationStatusSent   NotificationStatus = "sent"
	NotificationStatusFailed NotificationStatus = "failed"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type NotificationType string

const (
	NotificationTypeWhatsapp NotificationType = "whatsapp"
	NotificationTypeEmail    NotificationType = "email"
	NotificationTypeSms      NotificationType = "sms"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleOwner    UserRole = "owner"
	UserRoleEmployee UserRole = "employee"
	UserRoleCustomer UserRole = "customer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Appointment struct {
	ID             uuid.UUID         `json:"id"`
	SalonID        uuid.UUID         `json:"salon_id"`
	ProfessionalID uuid.UUID         `json:"professional_id"`
	ServiceID      uuid.UUID         `json:"service_id"`
	ClientName     string            `json:"client_name"`
	ClientPhone    string            `json:"client_phone"`
	ClientEmail    sql.NullString    `json:"client_email"`
	Date           time.Time         `json:"date"`
	StartTime      time.Time         `json:"start_time"`
	EndTime        time.Time         `json:"end_time"`
	Status         AppointmentStatus `json:"status"`
	Notes          sql.NullString    `json:"notes"`
	CreatedAt      time.Time         `json:"created_at"`
}

type Client struct {
	ID                uuid.UUID      `json:"id"`
	SalonID           uuid.UUID      `json:"salon_id"`
	Name              string         `json:"name"`
	Phone             string         `json:"phone"`
	Email             sql.NullString `json:"email"`
	Birthday          sql.NullTime   `json:"birthday"`
	TotalAppointments int32          `json:"total_appointments"`
	LastAppointment   sql.NullTime   `json:"last_appointment"`
	CreatedAt         time.Time      `json:"created_at"`
}

type ContactForm struct {
	ID          uuid.UUID          `json:"id"`
	FullName    string             `json:"full_name"`
	Email       string             `json:"email"`
	PhoneNumber sql.NullString     `json:"phone_number"`
	SalonName   sql.NullString     `json:"salon_name"`
	Subject     ContactFormSubject `json:"subject"`
	Message     string             `json:"message"`
	CreatedAt   time.Time          `json:"created_at"`
	AnsweredAt  sql.NullTime       `json:"answered_at"`
}

type Notification struct {
	ID            uuid.UUID          `json:"id"`
	AppointmentID uuid.UUID          `json:"appointment_id"`
	Type          NotificationType   `json:"type"`
	Status        NotificationStatus `json:"status"`
	ScheduledAt   time.Time          `json:"scheduled_at"`
	SentAt        sql.NullTime       `json:"sent_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Professional struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	SalonID   uuid.UUID      `json:"salon_id"`
	Name      string         `json:"name"`
	PhotoUrl  sql.NullString `json:"photo_url"`
	Active    bool           `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Salon struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	Slug          string          `json:"slug"`
	OwnerID       uuid.UUID       `json:"owner_id"`
	Address       string          `json:"address"`
	Whatsapp      sql.NullString  `json:"whatsapp"`
	Timezone      string          `json:"timezone"`
	BusinessHours json.RawMessage `json:"business_hours"`
	LogoUrl       sql.NullString  `json:"logo_url"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type Service struct {
	ID             uuid.UUID     `json:"id"`
	SalonID        uuid.UUID     `json:"salon_id"`
	ProfessionalID uuid.NullUUID `json:"professional_id"`
	Name           string        `json:"name"`
	Duration       int32         `json:"duration"`
	Price          int32         `json:"price"`
	Active         bool          `json:"active"`
	CreatedAt      time.Time     `json:"created_at"`
}

type Sso struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Provider       string         `json:"provider"`
	ProviderUserID string         `json:"provider_user_id"`
	AccessToken    sql.NullString `json:"access_token"`
	RefreshToken   sql.NullString `json:"refresh_token"`
	ExpiresAt      sql.NullTime   `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Name         string        `json:"name"`
	Phone        string        `json:"phone"`
	Role         UserRole      `json:"role"`
	SalonID      uuid.NullUUID `json:"salon_id"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}
