// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    appointment_id,
    type,
    scheduled_at
) VALUES (
    $1, $2, $3
) RETURNING id, appointment_id, type, status, scheduled_at, sent_at, created_at
`

type CreateNotificationParams struct {
	AppointmentID uuid.UUID        `json:"appointment_id"`
	Type          NotificationType `json:"type"`
	ScheduledAt   time.Time        `json:"scheduled_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification, arg.AppointmentID, arg.Type, arg.ScheduledAt)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Type,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const deleteNotificationsByAppointmentID = `-- name: DeleteNotificationsByAppointmentID :exec
DELETE FROM notifications
WHERE appointment_id = $1
`

func (q *Queries) DeleteNotificationsByAppointmentID(ctx context.Context, appointmentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByAppointmentID, appointmentID)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, appointment_id, type, status, scheduled_at, sent_at, created_at FROM notifications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Type,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByAppointmentID = `-- name: ListNotificationsByAppointmentID :many
SELECT id, appointment_id, type, status, scheduled_at, sent_at, created_at FROM notifications
WHERE appointment_id = $1
ORDER BY scheduled_at
`

func (q *Queries) ListNotificationsByAppointmentID(ctx context.Context, appointmentID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByAppointmentID, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.Type,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByStatus = `-- name: ListNotificationsByStatus :many
SELECT id, appointment_id, type, status, scheduled_at, sent_at, created_at FROM notifications
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNotificationsByStatusParams struct {
	Status NotificationStatus `json:"status"`
	Limit  int32              `json:"limit"`
}

func (q *Queries) ListNotificationsByStatus(ctx context.Context, arg ListNotificationsByStatusParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.Type,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT id, appointment_id, type, status, scheduled_at, sent_at, created_at FROM notifications
WHERE status = 'queued' AND scheduled_at <= NOW()
ORDER BY scheduled_at
LIMIT $1
`

func (q *Queries) ListPendingNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.Type,
			&i.Status,
			&i.ScheduledAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET 
    status = $2,
    sent_at = CASE WHEN $2 = 'sent' THEN NOW() ELSE sent_at END
WHERE id = $1
RETURNING id, appointment_id, type, status, scheduled_at, sent_at, created_at
`

type UpdateNotificationStatusParams struct {
	ID     uuid.UUID          `json:"id"`
	Status NotificationStatus `json:"status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationStatus, arg.ID, arg.Status)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Type,
		&i.Status,
		&i.ScheduledAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}
