// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const completeUserOnboarding = `-- name: CompleteUserOnboarding :exec
UPDATE users
SET current_onboarding_step_id = $2,
    onboarding_completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type CompleteUserOnboardingParams struct {
	ID                      uuid.UUID     `json:"id"`
	CurrentOnboardingStepID sql.NullInt32 `json:"current_onboarding_step_id"`
}

func (q *Queries) CompleteUserOnboarding(ctx context.Context, arg CompleteUserOnboardingParams) error {
	_, err := q.db.ExecContext(ctx, completeUserOnboarding, arg.ID, arg.CurrentOnboardingStepID)
	return err
}

const deleteAllUserOnboardingSelections = `-- name: DeleteAllUserOnboardingSelections :exec
DELETE FROM salon_onboarding_selection
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserOnboardingSelections(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserOnboardingSelections, userID)
	return err
}

const deleteUserOnboardingSelectionsByStep = `-- name: DeleteUserOnboardingSelectionsByStep :exec
DELETE FROM salon_onboarding_selection
WHERE user_id = $1 AND step_id = $2
`

type DeleteUserOnboardingSelectionsByStepParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	StepID int32         `json:"step_id"`
}

func (q *Queries) DeleteUserOnboardingSelectionsByStep(ctx context.Context, arg DeleteUserOnboardingSelectionsByStepParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserOnboardingSelectionsByStep, arg.UserID, arg.StepID)
	return err
}

const getAllOnboardingOptions = `-- name: GetAllOnboardingOptions :many
SELECT id, step_id, option_index, created_at FROM onboarding_options
ORDER BY step_id, option_index
`

func (q *Queries) GetAllOnboardingOptions(ctx context.Context) ([]OnboardingOption, error) {
	rows, err := q.db.QueryContext(ctx, getAllOnboardingOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnboardingOption
	for rows.Next() {
		var i OnboardingOption
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.OptionIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnboardingOptionsByStep = `-- name: GetOnboardingOptionsByStep :many
SELECT id, step_id, option_index, created_at FROM onboarding_options
WHERE step_id = $1
ORDER BY option_index
`

func (q *Queries) GetOnboardingOptionsByStep(ctx context.Context, stepID int32) ([]OnboardingOption, error) {
	rows, err := q.db.QueryContext(ctx, getOnboardingOptionsByStep, stepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OnboardingOption
	for rows.Next() {
		var i OnboardingOption
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.OptionIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnboardingSteps = `-- name: GetOnboardingSteps :many
SELECT id FROM onboarding_steps
ORDER BY id
`

func (q *Queries) GetOnboardingSteps(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getOnboardingSteps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOnboardingSelections = `-- name: GetUserOnboardingSelections :many
SELECT salon_id, step_id, option_index, user_id, chosen_at FROM salon_onboarding_selection
WHERE user_id = $1
ORDER BY step_id, option_index
`

func (q *Queries) GetUserOnboardingSelections(ctx context.Context, userID uuid.NullUUID) ([]SalonOnboardingSelection, error) {
	rows, err := q.db.QueryContext(ctx, getUserOnboardingSelections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalonOnboardingSelection
	for rows.Next() {
		var i SalonOnboardingSelection
		if err := rows.Scan(
			&i.SalonID,
			&i.StepID,
			&i.OptionIndex,
			&i.UserID,
			&i.ChosenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserOnboarding = `-- name: ResetUserOnboarding :exec
UPDATE users
SET current_onboarding_step_id = NULL,
    onboarding_completed_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetUserOnboarding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetUserOnboarding, id)
	return err
}

const saveOnboardingSelection = `-- name: SaveOnboardingSelection :exec
INSERT INTO salon_onboarding_selection (
    user_id,
    salon_id,
    step_id,
    option_index
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (salon_id, step_id, option_index) DO NOTHING
`

type SaveOnboardingSelectionParams struct {
	UserID      uuid.NullUUID `json:"user_id"`
	SalonID     uuid.UUID     `json:"salon_id"`
	StepID      int32         `json:"step_id"`
	OptionIndex int32         `json:"option_index"`
}

func (q *Queries) SaveOnboardingSelection(ctx context.Context, arg SaveOnboardingSelectionParams) error {
	_, err := q.db.ExecContext(ctx, saveOnboardingSelection,
		arg.UserID,
		arg.SalonID,
		arg.StepID,
		arg.OptionIndex,
	)
	return err
}

const updateUserOnboardingStep = `-- name: UpdateUserOnboardingStep :exec
UPDATE users
SET current_onboarding_step_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserOnboardingStepParams struct {
	ID                      uuid.UUID     `json:"id"`
	CurrentOnboardingStepID sql.NullInt32 `json:"current_onboarding_step_id"`
}

func (q *Queries) UpdateUserOnboardingStep(ctx context.Context, arg UpdateUserOnboardingStepParams) error {
	_, err := q.db.ExecContext(ctx, updateUserOnboardingStep, arg.ID, arg.CurrentOnboardingStepID)
	return err
}
