// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: professionals.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProfessional = `-- name: CreateProfessional :one
INSERT INTO professionals (
    user_id,
    salon_id,
    name,
    photo_url,
    active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, salon_id, name, photo_url, active, created_at, updated_at
`

type CreateProfessionalParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	SalonID  uuid.UUID      `json:"salon_id"`
	Name     string         `json:"name"`
	PhotoUrl sql.NullString `json:"photo_url"`
	Active   bool           `json:"active"`
}

func (q *Queries) CreateProfessional(ctx context.Context, arg CreateProfessionalParams) (Professional, error) {
	row := q.db.QueryRowContext(ctx, createProfessional,
		arg.UserID,
		arg.SalonID,
		arg.Name,
		arg.PhotoUrl,
		arg.Active,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalonID,
		&i.Name,
		&i.PhotoUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfessional = `-- name: DeleteProfessional :exec
DELETE FROM professionals
WHERE id = $1
`

func (q *Queries) DeleteProfessional(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfessional, id)
	return err
}

const getProfessionalByID = `-- name: GetProfessionalByID :one
SELECT id, user_id, salon_id, name, photo_url, active, created_at, updated_at FROM professionals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfessionalByID(ctx context.Context, id uuid.UUID) (Professional, error) {
	row := q.db.QueryRowContext(ctx, getProfessionalByID, id)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalonID,
		&i.Name,
		&i.PhotoUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfessionalByUserAndSalon = `-- name: GetProfessionalByUserAndSalon :one
SELECT id, user_id, salon_id, name, photo_url, active, created_at, updated_at FROM professionals
WHERE user_id = $1 AND salon_id = $2 LIMIT 1
`

type GetProfessionalByUserAndSalonParams struct {
	UserID  uuid.UUID `json:"user_id"`
	SalonID uuid.UUID `json:"salon_id"`
}

func (q *Queries) GetProfessionalByUserAndSalon(ctx context.Context, arg GetProfessionalByUserAndSalonParams) (Professional, error) {
	row := q.db.QueryRowContext(ctx, getProfessionalByUserAndSalon, arg.UserID, arg.SalonID)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalonID,
		&i.Name,
		&i.PhotoUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProfessionalsBySalonID = `-- name: ListActiveProfessionalsBySalonID :many
SELECT id, user_id, salon_id, name, photo_url, active, created_at, updated_at FROM professionals
WHERE salon_id = $1 AND active = true
ORDER BY name
`

func (q *Queries) ListActiveProfessionalsBySalonID(ctx context.Context, salonID uuid.UUID) ([]Professional, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProfessionalsBySalonID, salonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Professional
	for rows.Next() {
		var i Professional
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SalonID,
			&i.Name,
			&i.PhotoUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfessionalsBySalonID = `-- name: ListProfessionalsBySalonID :many
SELECT id, user_id, salon_id, name, photo_url, active, created_at, updated_at FROM professionals
WHERE salon_id = $1
ORDER BY name
`

func (q *Queries) ListProfessionalsBySalonID(ctx context.Context, salonID uuid.UUID) ([]Professional, error) {
	rows, err := q.db.QueryContext(ctx, listProfessionalsBySalonID, salonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Professional
	for rows.Next() {
		var i Professional
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SalonID,
			&i.Name,
			&i.PhotoUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfessional = `-- name: UpdateProfessional :one
UPDATE professionals
SET 
    name = COALESCE($2, name),
    photo_url = COALESCE($3, photo_url),
    active = COALESCE($4, active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, salon_id, name, photo_url, active, created_at, updated_at
`

type UpdateProfessionalParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     sql.NullString `json:"name"`
	PhotoUrl sql.NullString `json:"photo_url"`
	Active   sql.NullBool   `json:"active"`
}

func (q *Queries) UpdateProfessional(ctx context.Context, arg UpdateProfessionalParams) (Professional, error) {
	row := q.db.QueryRowContext(ctx, updateProfessional,
		arg.ID,
		arg.Name,
		arg.PhotoUrl,
		arg.Active,
	)
	var i Professional
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SalonID,
		&i.Name,
		&i.PhotoUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
