// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: salons.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSalon = `-- name: CreateSalon :one
INSERT INTO salons (
    name,
    slug,
    owner_id,
    address,
    whatsapp,
    business_hours,
    logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, slug, owner_id, address, whatsapp, business_hours, logo_url, created_at, updated_at
`

type CreateSalonParams struct {
	Name          string          `json:"name"`
	Slug          string          `json:"slug"`
	OwnerID       uuid.UUID       `json:"owner_id"`
	Address       string          `json:"address"`
	Whatsapp      sql.NullString  `json:"whatsapp"`
	BusinessHours json.RawMessage `json:"business_hours"`
	LogoUrl       sql.NullString  `json:"logo_url"`
}

func (q *Queries) CreateSalon(ctx context.Context, arg CreateSalonParams) (Salon, error) {
	row := q.db.QueryRowContext(ctx, createSalon,
		arg.Name,
		arg.Slug,
		arg.OwnerID,
		arg.Address,
		arg.Whatsapp,
		arg.BusinessHours,
		arg.LogoUrl,
	)
	var i Salon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.Address,
		&i.Whatsapp,
		&i.BusinessHours,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSalon = `-- name: DeleteSalon :exec
DELETE FROM salons
WHERE id = $1
`

func (q *Queries) DeleteSalon(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSalon, id)
	return err
}

const getSalonByID = `-- name: GetSalonByID :one
SELECT id, name, slug, owner_id, address, whatsapp, business_hours, logo_url, created_at, updated_at FROM salons
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSalonByID(ctx context.Context, id uuid.UUID) (Salon, error) {
	row := q.db.QueryRowContext(ctx, getSalonByID, id)
	var i Salon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.Address,
		&i.Whatsapp,
		&i.BusinessHours,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalonByOwnerID = `-- name: GetSalonByOwnerID :one
SELECT id, name, slug, owner_id, address, whatsapp, business_hours, logo_url, created_at, updated_at FROM salons
WHERE owner_id = $1 LIMIT 1
`

func (q *Queries) GetSalonByOwnerID(ctx context.Context, ownerID uuid.UUID) (Salon, error) {
	row := q.db.QueryRowContext(ctx, getSalonByOwnerID, ownerID)
	var i Salon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.Address,
		&i.Whatsapp,
		&i.BusinessHours,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalonBySlug = `-- name: GetSalonBySlug :one
SELECT id, name, slug, owner_id, address, whatsapp, business_hours, logo_url, created_at, updated_at FROM salons
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetSalonBySlug(ctx context.Context, slug string) (Salon, error) {
	row := q.db.QueryRowContext(ctx, getSalonBySlug, slug)
	var i Salon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.Address,
		&i.Whatsapp,
		&i.BusinessHours,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSalons = `-- name: ListSalons :many
SELECT id, name, slug, owner_id, address, whatsapp, business_hours, logo_url, created_at, updated_at FROM salons
ORDER BY created_at DESC
`

func (q *Queries) ListSalons(ctx context.Context) ([]Salon, error) {
	rows, err := q.db.QueryContext(ctx, listSalons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Salon
	for rows.Next() {
		var i Salon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.Address,
			&i.Whatsapp,
			&i.BusinessHours,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalon = `-- name: UpdateSalon :one
UPDATE salons
SET 
    name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    address = COALESCE($4, address),
    whatsapp = COALESCE($5, whatsapp),
    business_hours = COALESCE($6, business_hours),
    logo_url = COALESCE($7, logo_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, owner_id, address, whatsapp, business_hours, logo_url, created_at, updated_at
`

type UpdateSalonParams struct {
	ID            uuid.UUID             `json:"id"`
	Name          sql.NullString        `json:"name"`
	Slug          sql.NullString        `json:"slug"`
	Address       sql.NullString        `json:"address"`
	Whatsapp      sql.NullString        `json:"whatsapp"`
	BusinessHours pqtype.NullRawMessage `json:"business_hours"`
	LogoUrl       sql.NullString        `json:"logo_url"`
}

func (q *Queries) UpdateSalon(ctx context.Context, arg UpdateSalonParams) (Salon, error) {
	row := q.db.QueryRowContext(ctx, updateSalon,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Address,
		arg.Whatsapp,
		arg.BusinessHours,
		arg.LogoUrl,
	)
	var i Salon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.Address,
		&i.Whatsapp,
		&i.BusinessHours,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
