// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    salon_id,
    professional_id,
    name,
    duration,
    price,
    active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, salon_id, professional_id, name, duration, price, active, created_at
`

type CreateServiceParams struct {
	SalonID        uuid.UUID     `json:"salon_id"`
	ProfessionalID uuid.NullUUID `json:"professional_id"`
	Name           string        `json:"name"`
	Duration       int32         `json:"duration"`
	Price          int32         `json:"price"`
	Active         bool          `json:"active"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.SalonID,
		arg.ProfessionalID,
		arg.Name,
		arg.Duration,
		arg.Price,
		arg.Active,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.ProfessionalID,
		&i.Name,
		&i.Duration,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, salon_id, professional_id, name, duration, price, active, created_at FROM services
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.ProfessionalID,
		&i.Name,
		&i.Duration,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveServicesBySalonID = `-- name: ListActiveServicesBySalonID :many
SELECT id, salon_id, professional_id, name, duration, price, active, created_at FROM services
WHERE salon_id = $1 AND active = true
ORDER BY name
`

func (q *Queries) ListActiveServicesBySalonID(ctx context.Context, salonID uuid.UUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServicesBySalonID, salonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.ProfessionalID,
			&i.Name,
			&i.Duration,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProfessionalID = `-- name: ListServicesByProfessionalID :many
SELECT id, salon_id, professional_id, name, duration, price, active, created_at FROM services
WHERE professional_id = $1 AND active = true
ORDER BY name
`

func (q *Queries) ListServicesByProfessionalID(ctx context.Context, professionalID uuid.NullUUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesByProfessionalID, professionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.ProfessionalID,
			&i.Name,
			&i.Duration,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesBySalonAndProfessional = `-- name: ListServicesBySalonAndProfessional :many
SELECT id, salon_id, professional_id, name, duration, price, active, created_at FROM services
WHERE salon_id = $1 AND (professional_id = $2 OR professional_id IS NULL) AND active = true
ORDER BY name
`

type ListServicesBySalonAndProfessionalParams struct {
	SalonID        uuid.UUID     `json:"salon_id"`
	ProfessionalID uuid.NullUUID `json:"professional_id"`
}

func (q *Queries) ListServicesBySalonAndProfessional(ctx context.Context, arg ListServicesBySalonAndProfessionalParams) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesBySalonAndProfessional, arg.SalonID, arg.ProfessionalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.ProfessionalID,
			&i.Name,
			&i.Duration,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesBySalonID = `-- name: ListServicesBySalonID :many
SELECT id, salon_id, professional_id, name, duration, price, active, created_at FROM services
WHERE salon_id = $1
ORDER BY name
`

func (q *Queries) ListServicesBySalonID(ctx context.Context, salonID uuid.UUID) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesBySalonID, salonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.SalonID,
			&i.ProfessionalID,
			&i.Name,
			&i.Duration,
			&i.Price,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET 
    name = COALESCE($2, name),
    duration = COALESCE($3, duration),
    price = COALESCE($4, price),
    active = COALESCE($5, active),
    professional_id = COALESCE($6, professional_id)
WHERE id = $1
RETURNING id, salon_id, professional_id, name, duration, price, active, created_at
`

type UpdateServiceParams struct {
	ID             uuid.UUID      `json:"id"`
	Name           sql.NullString `json:"name"`
	Duration       sql.NullInt32  `json:"duration"`
	Price          sql.NullInt32  `json:"price"`
	Active         sql.NullBool   `json:"active"`
	ProfessionalID uuid.NullUUID  `json:"professional_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Duration,
		arg.Price,
		arg.Active,
		arg.ProfessionalID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.SalonID,
		&i.ProfessionalID,
		&i.Name,
		&i.Duration,
		&i.Price,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
