// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSSO = `-- name: CreateSSO :one
INSERT INTO sso (
    user_id,
    provider,
    provider_user_id
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, provider, provider_user_id, created_at, updated_at
`

type CreateSSOParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
}

func (q *Queries) CreateSSO(ctx context.Context, arg CreateSSOParams) (Sso, error) {
	row := q.db.QueryRowContext(ctx, createSSO, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i Sso
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSSO = `-- name: DeleteSSO :exec
DELETE FROM sso
WHERE id = $1
`

func (q *Queries) DeleteSSO(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSSO, id)
	return err
}

const deleteSSOByUserID = `-- name: DeleteSSOByUserID :exec
DELETE FROM sso
WHERE user_id = $1
`

func (q *Queries) DeleteSSOByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSSOByUserID, userID)
	return err
}

const getSSOByProvider = `-- name: GetSSOByProvider :one
SELECT id, user_id, provider, provider_user_id, created_at, updated_at FROM sso
WHERE provider = $1 AND provider_user_id = $2 LIMIT 1
`

type GetSSOByProviderParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetSSOByProvider(ctx context.Context, arg GetSSOByProviderParams) (Sso, error) {
	row := q.db.QueryRowContext(ctx, getSSOByProvider, arg.Provider, arg.ProviderUserID)
	var i Sso
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOByUserID = `-- name: GetSSOByUserID :many
SELECT id, user_id, provider, provider_user_id, created_at, updated_at FROM sso
WHERE user_id = $1
`

func (q *Queries) GetSSOByUserID(ctx context.Context, userID uuid.UUID) ([]Sso, error) {
	rows, err := q.db.QueryContext(ctx, getSSOByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sso
	for rows.Next() {
		var i Sso
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
